#!/bin/bash


# Set decoration geometry
berryc border_width       5
berryc inner_border_width 3
berryc title_height       30
berryc top_gap            30

# Set decoration colors
berryc focus_color         292D3E
berryc unfocus_color       292D3E
berryc inner_focus_color   FFCB6B
berryc inner_unfocus_color 565679
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Dina-9"





## Set Cursor
xsetroot -cursor_name left_ptr


## autostart
compton --config "$HOME/.config/berry/compton/compton.conf" &

wallpaper.sh

sxhkd -c "$HOME/.config/berry/sxhkdrc" &

tint2 -c "$HOME/.config/berry/tint2/tint2rc" &

mate-volume-control-status-icon &

fcitx &

nm-applet &
