
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [command]'
	@echo
	@echo 'Ex:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make to_example'
	@echo



.PHONY: help


to_example:
	@./default-change.sh example
.PHONY: example


