
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [command]'
	@echo
	@echo 'Ex:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make to_default'
	@echo '	$$ make to_example'
	@echo '	$$ make to_kb1'
	@echo



.PHONY: help


to_example:
	@./default-change.sh example
.PHONY: example


to_kb1:
	@./default-change.sh kb1
.PHONY: to_kb1


to_default:
	@./default-change.sh kb1
.PHONY: to_default

