#!/bin/bash


# https://berrywm.org/configuration.html

## Set decoration geometry
berryc border_width       2
berryc inner_border_width 0
berryc title_height       24
berryc top_gap            42
berryc edge_gap           46 10 10 10

## Set decoration colors
berryc focus_color         555555
berryc unfocus_color       323232
berryc inner_focus_color   404040
berryc inner_unfocus_color 303030
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

## Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
#berryc set_font    "Dina-9"
berryc set_font    "Sans-12"


## workspace
berryc name_desktop 0 "Term"
berryc name_desktop 1 "Edit"
berryc name_desktop 2 "Web"
berryc name_desktop 3 "File"
berryc name_desktop 4 "Misc"





## Set Cursor
xsetroot -cursor_name left_ptr


## autostart
compton --config "$HOME/.config/berry/compton/compton.conf" &

wallpaper.sh

sxhkd -c "$HOME/.config/berry/sxhkdrc" &

tint2 -c "$HOME/.config/berry/tint2/tint2rc" &

mate-volume-control-status-icon &

fcitx &

nm-applet &
